const Categories = [
  "1010 Block",
  "2048 & Merge",
  "3D Mahjong",
  "Arkanoid",
  "Bejeweled",
  "Billiards",
  "Board",
  "Brain Games",
  "Bubble Shooter",
  "Card Games",
  "Collapse Games",
  "Connect 3",
  "Crosswords",
  "Daily Puzzles",
  "Difference Games",
  "Escape Games",
  "Freecell",
  "Golf",
  "Hidden Alphabet",
  "Hidden Clues",
  "Hidden Numbers",
  "Hidden Object Games",
  "Klondike",
  "Mahjong Connect",
  "Mahjong Games",
  "Mahjong Slide",
  "Mahjong Solitaire",
  "Mahjong Tower",
  "Match 3 Games",
  "Math Games",
  "Maze Games",
  "Memory",
  "Montana",
  "Pac Maze",
  "Pinball",
  "Platform",
  "Puzzle Games",
  "Puzzles",
  "Pyramid",
  "Racing",
  "Retro",
  "Shooting & War",
  "Skill",
  "Snake",
  "Solitaire Games",
  "Sorting Games",
  "Spider",
  "Sudoku",
  "Tetris",
  "Tile Games",
  "Time management",
  "Tower Defense",
  "Tripeaks & Golf",
  "Word Games",
  "Zuma Games",
  "3D","Action","Casual","Driving","Girls","Logic","MMO","Multiplayer","Sports","Strategy",
];

export default Categories;
